var pokemonList = [
  "Bulbasaur",
  "Ivysaur",
  "Venusaur",
  "Charmander",
  "Charmeleon",
  "Charizard",
  "Squirtle",
  "Wartortle",
  "Blastoise",
  "Caterpie",
  "Metapod",
  "Butterfree",
  "Weedle",
  "Kakuna",
  "Beedrill",
  "Pidgey",
  "Pidgeotto",
  "Pidgeot",
  "Rattata",
  "Alolan Rattata",
  "Raticate",
  "Alolan Raticate",
  "Spearow",
  "Fearow",
  "Ekans",
  "Arbok",
  "Pikachu",
  "Raichu",
  "Alolan Raichu",
  "Sandshrew",
  "Alolan Sandshrew",
  "Sandslash",
  "Alolan Sandslash",
  "Nidoran ♀",
  "Nidorina",
  "Nidoqueen",
  "Nidoran ♂",
  "Nidorino",
  "Nidoking",
  "Clefairy",
  "Clefable",
  "Vulpix",
  "Alolan Vulpix",
  "Ninetales",
  "Alolan Ninetales",
  "Jigglypuff",
  "Wigglytuff",
  "Zubat",
  "Golbat",
  "Oddish",
  "Gloom",
  "Vileplume",
  "Paras",
  "Parasect",
  "Venonat",
  "Venomoth",
  "Diglett",
  "Alolan Diglett",
  "Dugtrio",
  "Alolan Dugtrio",
  "Meowth",
  "Alolan Meowth",
  "Persian",
  "Alolan Persian",
  "Psyduck",
  "Golduck",
  "Mankey",
  "Primeape",
  "Growlithe",
  "Arcanine",
  "Poliwag",
  "Poliwhirl",
  "Poliwrath",
  "Abra",
  "Kadabra",
  "Alakazam",
  "Machop",
  "Machoke",
  "Machamp",
  "Bellsprout",
  "Weepinbell",
  "Victreebel",
  "Tentacool",
  "Tentacruel",
  "Geodude",
  "Alolan Geodude",
  "Graveler",
  "Alolan Gravler",
  "Golem",
  "Alolan Golem",
  "Ponyta",
  "Rapidash",
  "Slowpoke",
  "Slowbro",
  "Magnemite",
  "Magneton",
  "Farfetch’d",
  "Doduo",
  "Dodrio",
  "Seel",
  "Dewgong",
  "Grimer",
  "Alolan Grimer",
  "Muk",
  "Alolan Muk",
  "Shellder",
  "Cloyster",
  "Gastly",
  "Haunter",
  "Gengar",
  "Onix",
  "Drowzee",
  "Hypno",
  "Krabby",
  "Kingler",
  "Voltorb",
  "Electrode",
  "Exeggcute",
  "Exeggutor",
  "Alolan Exeggutor",
  "Cubone",
  "Marowak",
  "Alolan Marowak",
  "Hitmonlee",
  "Hitmonchan",
  "Lickitung",
  "Koffing",
  "Weezing",
  "Rhyhorn",
  "Rhydon",
  "Chansey",
  "Tangela",
  "Kangaskhan",
  "Horsea",
  "Seadra",
  "Goldeen",
  "Seaking",
  "Staryu",
  "Starmie",
  "Mr. Mime",
  "Scyther",
  "Jynx",
  "Electabuzz",
  "Magmar",
  "Pinsir",
  "Tauros",
  "Magikarp",
  "Gyarados",
  "Lapras",
  "Ditto",
  "Eevee",
  "Vaporeon",
  "Jolteon",
  "Flareon",
  "Porygon",
  "Omanyte",
  "Omastar",
  "Kabuto",
  "Kabutops",
  "Aerodactyl",
  "Snorlax",
  "Dratini",
  "Dragonair",
  "Dragonite",
  "Chikorita",
  "Bayleef",
  "Meganium",
  "Cyndaquil",
  "Quilava",
  "Typhlosion",
  "Totodile",
  "Croconaw",
  "Feraligatr",
  "Sentret",
  "Furret",
  "Hoothoot",
  "Noctowl",
  "Ledyba",
  "Ledian",
  "Spinarak",
  "Ariados",
  "Crobat",
  "Chinchou",
  "Lanturn",
  "Pichu",
  "Cleffa",
  "Igglybuff",
  "Togepi",
  "Togetic",
  "Natu",
  "Xatu",
  "Mareep",
  "Flaaffy",
  "Ampharos",
  "Bellossom",
  "Marill",
  "Azumarill",
  "Sudowoodo",
  "Politoed",
  "Hoppip",
  "Skiploom",
  "Jumpluff",
  "Aipom",
  "Sunkern",
  "Sunflora",
  "Yanma",
  "Wooper",
  "Quagsire",
  "Espeon",
  "Umbreon",
  "Murkrow",
  "Slowking",
  "Misdreavus",
  "Unown",
  "Wobbuffet",
  "Girafarig",
  "Pineco",
  "Forretress",
  "Dunsparce",
  "Gligar",
  "Steelix",
  "Snubbull",
  "Granbull",
  "Qwilfish",
  "Scizor",
  "Shuckle",
  "Heracross",
  "Sneasel",
  "Teddiursa",
  "Ursaring",
  "Slugma",
  "Magcargo",
  "Swinub",
  "Piloswine",
  "Corsola",
  "Remoraid",
  "Octillery",
  "Delibird",
  "Mantine",
  "Skarmory",
  "Houndour",
  "Houndoom",
  "Kingdra",
  "Phanpy",
  "Donphan",
  "Porygon2",
  "Stantler",
  "Smeargle",
  "Tyrogue",
  "Hitmontop",
  "Smoochum",
  "Elekid",
  "Magby",
  "Miltank",
  "Blissey",
  "Larvitar",
  "Pupitar",
  "Tyranitar",
  "Treecko",
  "Grovyle",
  "Sceptile",
  "Torchic",
  "Combusken",
  "Blaziken",
  "Mudkip",
  "Marshtomp",
  "Swampert",
  "Poochyena",
  "Mightyena",
  "Zigzagoon",
  "Linoone",
  "Wurmple",
  "Silcoon",
  "Beautifly",
  "Cascoon",
  "Dustox",
  "Lotad",
  "Lombre",
  "Ludicolo",
  "Seedot",
  "Nuzleaf",
  "Shiftry",
  "Taillow",
  "Swellow",
  "Wingull",
  "Pelipper",
  "Ralts",
  "Kirlia",
  "Gardevoir",
  "Surskit",
  "Masquerain",
  "Shroomish",
  "Breloom",
  "Slakoth",
  "Vigoroth",
  "Slaking",
  "Nincada",
  "Ninjask",
  "Shedinja",
  "Whismur",
  "Loudred",
  "Exploud",
  "Makuhita",
  "Hariyama",
  "Azurill",
  "Nosepass",
  "Skitty",
  "Delcatty",
  "Sableye",
  "Mawile",
  "Aron",
  "Lairon",
  "Aggron",
  "Meditite",
  "Medicham",
  "Electrike",
  "Manectric",
  "Plusle",
  "Minun",
  "Volbeat",
  "Illumise",
  "Roselia",
  "Gulpin",
  "Swalot",
  "Carvanha",
  "Sharpedo",
  "Wailmer",
  "Wailord",
  "Numel",
  "Camerupt",
  "Torkoal",
  "Spoink",
  "Grumpig",
  "Spinda",
  "Trapinch",
  "Vibrava",
  "Flygon",
  "Cacnea",
  "Cacturne",
  "Swablu",
  "Altaria",
  "Zangoose",
  "Seviper",
  "Lunatone",
  "Solrock",
  "Barboach",
  "Whiscash",
  "Corphish",
  "Crawdaunt",
  "Baltoy",
  "Claydol",
  "Lileep",
  "Cradily",
  "Anorith",
  "Armaldo",
  "Feebas",
  "Milotic",
  "Castform",
  "Kecleon",
  "Shuppet",
  "Banette",
  "Duskull",
  "Dusclops",
  "Tropius",
  "Chimecho",
  "Absol",
  "Wynaut",
  "Snorunt",
  "Glalie",
  "Spheal",
  "Sealeo",
  "Walrein",
  "Clamperl",
  "Huntail",
  "Gorebyss",
  "Relicanth",
  "Luvdisc",
  "Bagon",
  "Shelgon",
  "Salamence",
  "Beldum",
  "Metang",
  "Metagross",
  "Turtwig",
  "Grotle",
  "Torterra",
  "Chimchar",
  "Monferno",
  "Infernape",
  "Piplup",
  "Prinplup",
  "Empoleon",
  "Starly",
  "Staravia",
  "Staraptor",
  "Bidoof",
  "Bibarel",
  "Kricketot",
  "Kricketune",
  "Shinx",
  "Luxio",
  "Luxray",
  "Budew",
  "Roserade",
  "Cranidos",
  "Rampardos",
  "Shieldon",
  "Bastiodon",
  "Burmy",
  "Wormadam",
  "Mothim",
  "Combee",
  "Vespiquen",
  "Pachirisu",
  "Buizel",
  "Floatzel",
  "Cherubi",
  "Cherrim",
  "Shellos",
  "Gastrodon",
  "Ambipom",
  "Drifloon",
  "Drifblim",
  "Buneary",
  "Lopunny",
  "Mismagius",
  "Honchkrow",
  "Glameow",
  "Purugly",
  "Chingling",
  "Stunky",
  "Skuntank",
  "Bronzor",
  "Bronzong",
  "Bonsly",
  "Mime Jr.",
  "Happiny",
  "Chatot",
  "Spiritomb",
  "Gible",
  "Gabite",
  "Garchomp",
  "Munchlax",
  "Riolu",
  "Lucario",
  "Hippopotas",
  "Hippowdon",
  "Skorupi",
  "Drapion",
  "Croagunk",
  "Toxicroak",
  "Carnivine",
  "Finneon",
  "Lumineon",
  "Mantyke",
  "Snover",
  "Abomasnow",
  "Weavile",
  "Magnezone",
  "Lickilicky",
  "Rhyperior",
  "Tangrowth",
  "Electivire",
  "Magmortar",
  "Togekiss",
  "Yanmega",
  "Leafeon",
  "Glaceon",
  "Gliscor",
  "Mamoswine",
  "Porygon-Z",
  "Gallade",
  "Probopass",
  "Dusknoir",
  "Froslass",
  "Rotom",
  "Snivy",
  "Servine",
  "Serperior",
  "Tepig",
  "Pignite",
  "Emboar",
  "Oshawott",
  "Dewott",
  "Samurott",
  "Patrat",
  "Watchog",
  "Lillipup",
  "Herdier",
  "Stoutland",
  "Purrloin",
  "Liepard",
  "Pansage",
  "Simisage",
  "Pansear",
  "Simisear",
  "Panpour",
  "Simipour",
  "Munna",
  "Musharna",
  "Pidove",
  "Tranquill",
  "Unfezant",
  "Blitzle",
  "Zebstrika",
  "Roggenrola",
  "Boldore",
  "Gigalith",
  "Woobat",
  "Swoobat",
  "Drilbur",
  "Excadrill",
  "Audino",
  "Timburr",
  "Gurdurr",
  "Conkeldurr",
  "Tympole",
  "Palpitoad",
  "Seismitoad",
  "Throh",
  "Sawk",
  "Sewaddle",
  "Swadloon",
  "Leavanny",
  "Venipede",
  "Whirlipede",
  "Scolipede",
  "Cottonee",
  "Whimsicott",
  "Petilil",
  "Lilligant",
  "Basculin",
  "Sandile",
  "Krokorok",
  "Krookodile",
  "Darumaka",
  "Darmanitan",
  "Maractus",
  "Dwebble",
  "Crustle",
  "Scraggy",
  "Scrafty",
  "Sigilyph",
  "Yamask",
  "Cofagrigus",
  "Tirtouga",
  "Carracosta",
  "Archen",
  "Archeops",
  "Trubbish",
  "Garbodor",
  "Zorua",
  "Zoroark",
  "Minccino",
  "Cinccino",
  "Gothita",
  "Gothorita",
  "Gothitelle",
  "Solosis",
  "Duosion",
  "Reuniclus",
  "Ducklett",
  "Swanna",
  "Vanillite",
  "Vanillish",
  "Vanilluxe",
  "Deerling",
  "Sawsbuck",
  "Emolga",
  "Karrablast",
  "Escavalier",
  "Foongus",
  "Amoonguss",
  "Frillish",
  "Jellicent",
  "Alomomola",
  "Joltik",
  "Galvantula",
  "Ferroseed",
  "Ferrothorn",
  "Klink",
  "Klang",
  "Klinklang",
  "Tynamo",
  "Eelektrik",
  "Eelektross",
  "Elgyem",
  "Beheeyem",
  "Litwick",
  "Lampent",
  "Chandelure",
  "Axew",
  "Fraxure",
  "Haxorus",
  "Cubchoo",
  "Beartic",
  "Cryogonal",
  "Shelmet",
  "Accelgor",
  "Stunfisk",
  "Mienfoo",
  "Mienshao",
  "Druddigon",
  "Golett",
  "Golurk",
  "Pawniard",
  "Bisharp",
  "Bouffalant",
  "Rufflet",
  "Braviary",
  "Vullaby",
  "Mandibuzz",
  "Heatmor",
  "Durant",
  "Deino",
  "Zweilous",
  "Hydreigon",
  "Larvesta",
  "Volcarona",
  "Chespin",
  "Quilladin",
  "Chesnaught",
  "Fennekin",
  "Braixen",
  "Delphox",
  "Froakie",
  "Frogadier",
  "Greninja",
  "Bunnelby",
  "Diggersby",
  "Fletchling",
  "Fletchinder",
  "Talonflame",
  "Scatterbug",
  "Spewpa",
  "Vivillon",
  "Litleo",
  "Pyroar",
  "Flabebe",
  "Floette",
  "Florges",
  "Skiddo",
  "Gogoat",
  "Pancham",
  "Pangoro",
  "Furfrou",
  "Espurr",
  "Meowstic",
  "Honedge",
  "Doublade",
  "Aegislash",
  "Spritzee",
  "Aromatisse",
  "Swirlix",
  "Slurpuff",
  "Inkay",
  "Malamar",
  "Binacle",
  "Barbaracle",
  "Skrelp",
  "Dragalge",
  "Clauncher",
  "Clawitzer",
  "Helioptile",
  "Heliolisk",
  "Tyrunt",
  "Tyrantrum",
  "Amaura",
  "Aurorus",
  "Sylveon",
  "Hawlucha",
  "Dedenne",
  "Carbink",
  "Goomy",
  "Sliggoo",
  "Goodra",
  "Klefki",
  "Phantump",
  "Trevenant",
  "Pumpkaboo",
  "Gourgeist",
  "Bergmite",
  "Avalugg",
  "Noibat",
  "Noivern",
  "Rowlet",
  "Dartrix",
  "Decidueye",
  "Litten",
  "Torracat",
  "Incineroar",
  "Popplio",
  "Brionne",
  "Primarina",
  "Pikipek",
  "Trumbeak",
  "Toucannon",
  "Yungoos",
  "Gumshoos",
  "Grubbin",
  "Charjabug",
  "Vikavolt",
  "Crabrawler",
  "Crabominable",
  "Oricorio",
  "Cutiefly",
  "Ribombee",
  "Rockruff",
  "Lycanroc",
  "Wishiwashi",
  "Mareanie",
  "Toxapex",
  "Mudbray",
  "Mudsdale",
  "Dewpider",
  "Araquanid",
  "Fomantis",
  "Lurantis",
  "Morelull",
  "Shiinotic",
  "Salandit",
  "Salazzle",
  "Stufful",
  "Bewear",
  "Bounsweet",
  "Steenee",
  "Tsareena",
  "Comfey",
  "Oranguru",
  "Passimian",
  "Wimpod",
  "Golisopod",
  "Sandygast",
  "Palossand",
  "Pyukumuku",
  "Minior",
  "Komala",
  "Turtonator",
  "Togedemaru",
  "Mimikyu",
  "Bruxish",
  "Drampa",
  "Dhelmise",
  "Jangmo-o",
  "Hakamo-o",
  "Kommo-o",
  "Grookey",
  "Thwackey",
  "Rillaboom",
  "Scorbunny",
  "Raboot",
  "Cinderace",
  "Sobble",
  "Drizzile",
  "Inteleon",
  "Blipbug",
  "Dottler",
  "Orbeetle",
  "Rookidee",
  "Corvisquire",
  "Corviknight",
  "Skwovet",
  "Greedent",
  "Nickit",
  "Thievul",
  "Galarian Zigzagoon",
  "Galarian Linoone",
  "Obstagoon",
  "Wooloo",
  "Dubwool",
  "Chewtle",
  "Drednaw",
  "Yamper",
  "Boltund",
  "Gossifleur",
  "Eldegoss",
  "Sizzlipede",
  "Centiskorch",
  "Rolycoly",
  "Carkol",
  "Coalossal",
  "Arrokuda",
  "Barraskewda",
  "Galarian Meowth",
  "Perrserker",
  "Milcery",
  "Alcremie",
  "Applin",
  "Flapple",
  "Appletun",
  "Galarian Farfetch'd",
  "Sirfetch'd",
  "Galarian Stunfisk",
  "Galarian Corsola",
  "Cursola",
  "Impidimp",
  "Morgrem",
  "Grimmsnarl",
  "Hatenna",
  "Hattrem",
  "Hatterene",
  "Galarian Weezing",
  "Cufant",
  "Copperajah",
  "Cramorant",
  "Toxel",
  "Toxtricity",
  "Silicobra",
  "Sandaconda",
  "Galarian Yamask",
  "Runerigus",
  "Galarian Ponyta",
  "Galarian Rapidash",
  "Sinistea",
  "Phony Polteageist",
  "Antique Polteageist",
  "Indeedee",
  "Morpeko",
  "Falinks",
  "Snom",
  "Frosmoth",
  "Clobbopus",
  "Grapploct",
  "Pincurchin",
  "Galarian Mr. Mime",
  "Mr. Rime",
  "Galarian Darumaka",
  "Galarian Darmanitan",
  "Stonjourner",
  "Eiscue",
  "Duraludon",
  "Dracozolt",
  "Actrozolt",
  "Dracovish",
  "Arctovish",
  "Dreepy",
  "Drakloak",
  "Dragapult"
];

var legendaryList = [
  "Articuno",
  "Zapdos",
  "Moltres",
  "Mewtwo",
  "Mew",
  "Raikou",
  "Entei",
  "Suicune",
  "Lugia",
  "Ho-oh",
  "Celebi",
  "Regirock",
  "Regice",
  "Registeel",
  "Deoxys",
  "Groudon",
  "Kyogre",
  "Rayquaza",
  "Jirachi",
  "Latias",
  "Latios",
  "Dialga",
  "Palkia",
  "Giratina",
  "Heatran",
  "Regigigas",
  "Cresselia",
  "Phione",
  "Manaphy",
  "Darkrai",
  "Cresselia",
  "Shaymin",
  "Arceus",
  "Victini",
  "Cobalion",
  "Virizion",
  "Terrakion",
  "Zekrom",
  "Reshiram",
  "Landorus",
  "Tornadus",
  "Thundurus",
  "Kyurem",
  "Keldeo",
  "Meloetta",
  "Genesect",
  "Xerneas",
  "Yveltal",
  "Zygarde",
  "Diancie",
  "Hoopa",
  "Volcanion",
  "Tapu Koko",
  "Tapu Bulu",
  "Tapu Fini",
  "Tapu Lele",
  "Cosmog",
  "Cosmoem",
  "Solgaleo",
  "Lunala",
  "Nihilego",
  "Buzzwole",
  "Pheromosa",
  "Xurkitree",
  "Celesteela",
  "Kartana",
  "Guzzlord",
  "Necrozma",
  "Magearna",
  "Marshadow",
  "Poipole",
  "Naganadel",
  "Stakataka",
  "Blacephalon",
  "Zeraora",
  "Meltan",
  "Melmetal",
  "Zacian",
  "Zamazenta",
  "Eternatus",
  "Type: Null",
  "Silvally"
];

var typeList = [
  "Normal",
  "Fighting",
  "Ghost",
  "Dark",
  "Psychic",
  "Fairy",
  "Flying",
  "Electric",
  "Water",
  "Fire",
  "Grass",
  "Poison",
  "Steel",
  "Dragon",
  "Bug",
  "Ice",
  "Rock",
  "Ground",
  "Void",
  "Nova"
];

var moveList = [
  "Absorb",
  "Vaccum Wave",
  "Clamp",
  "Constrict",
  "Peck",
  "Whirlpool",
  "Acid",
  "Acid Spray",
  "Bind",
  "Bubble",
  "Bullet Punch",
  "Disarming Voice",
  "Dragon Rage",
  "Dual Chop",
  "Ember",
  "Fairy Wind",
  "False Swipe",
  "Gust",
  "Hold Back",
  "Ice Shard",
  "Infestation",
  "Leafage",
  "Mach Punch",
  "Mega Drain",
  "Mud Slap",
  "Nuzzle",
  "Pay Day",
  "Poison Sting",
  "Pound",
  "Powder Snow",
  "Power Up Punch",
  "Pursuit",
  "Quick Attack",
  "Rock Smash",
  "Sand Tomb",
  "Scratch",
  "Shadow Sneak",
  "Sonic Boom",
  "Tackle",
  "Thundershock",
  "Twister",
  "Water Gun",
  "Wrap",
  "Astonish",
  "Double Kick",
  "Lick",
  "Smog",
  "Twin Needle",
  "Vine Whip",
  "Accelerock",
  "Assist",
  "Barrage",
  "Bonemerang",
  "Bullet Seed",
  "Clear Smog",
  "Comet Punch",
  "Confusion",
  "Cut",
  "Double Slap",
  "Draining Kiss",
  "Echoed Voice",
  "Electro Ball",
  "Feint",
  "Fell Stinger",
  "Flame Charge",
  "Fury Attack",
  "Fury Cutter",
  "Fury Swipes",
  "Gear Grind",
  "Karate Chop",
  "Low Kick",
  "Metal claw",
  "Nature Power",
  "Nightmare",
  "Payback",
  "Pin Missile",
  "Poison Fang",
  "Poison Tail",
  "Psywave",
  "Rapid Spin",
  "Rock Throw",
  "Shadow Rush",
  "Smack Down",
  "Snore",
  "Spike Cannon",
  "Struggle Bug",
  "Water Shuriken",
  "Weather Ball (Fire)",
  "Weather Ball (Ice)",
  "Weather Ball (Normal)",
  "Weather Ball (Rock)",
  "Weather Ball (Water)",
  "Aqua Jet",
  "Arm Thrust",
  "Bone Rush",
  "Electro Web",
  "Fire Spin",
  "Icicle Spear",
  "Icy Wind",
  "Mud Shot",
  "Razor Leaf",
  "Snarl",
  "Tail Slap",
  "Vice Grip",
  "Aerial Ace",
  "Air Cutter",
  "Ancient Power",
  "Assurance",
  "Avalanche",
  "Beat Up",
  "Bide",
  "Bite",
  "Brutal Swing",
  "Bug Bite",
  "Bulldoze",
  "Charge Beam",
  "Circle Throw",
  "Copycat",
  "Covet",
  "Double Hit",
  "Dragon Tail",
  "Fake Out",
  "Feint Attack",
  "Flail",
  "Flame Wheel",
  "Fling",
  "Force Palm",
  "Frost Breath",
  "Heart Stamp",
  "Incinerate",
  "Magical Leaf",
  "Magnet Bomb",
  "Me First",
  "Mirror Move",
  "Natural Gift",
  "Needle Arm",
  "Night Shade",
  "Ominous Wind",
  "Pluck",
  "Rage",
  "Revenge",
  "Rock Blast",
  "Rock Tomb",
  "Rolling Kick",
  "Rollout",
  "Round",
  "Seismic Toss",
  "Shadow Punch",
  "Shock Wave",
  "Silver Wind",
  "Sky Drop",
  "Stored Power",
  "Storm Throw",
  "Super Fang",
  "Swift",
  "Thief",
  "Triple Kick",
  "Water Pulse",
  "Wing Attack",
  "Aurora Beam",
  "Bone Club",
  "Bubble Beam",
  "Fire Fang",
  "Glaciate",
  "Heat Crash",
  "Hex",
  "Horn Attack",
  "Ice Fang",
  "Knock Off",
  "Leaf Tornado",
  "Low Sweep",
  "Magnitude",
  "Mirror Shot",
  "Mud Bomb",
  "Octazooka",
  "Parabolic Charge",
  "Psybeam",
  "Sludge",
  "Spark",
  "Steamroller",
  "Stomp",
  "Thunder Fang",
  "Venoshock",
  "Chip Away",
  "Cross Poison",
  "Dizzy Punch",
  "Facade",
  "Flame Burst",
  "Freeze Dry",
  "Headbutt",
  "Luster Purge",
  "Mist Ball",
  "Night Slash",
  "Psycho Cut",
  "Retaliate",
  "Secret Power",
  "Shadow Claw",
  "Slash",
  "Smart Strike",
  "Smelling Salts",
  "Spit Up",
  "Steel Wing",
  "Sucker Punch",
  "Trop Kick",
  "U-turn",
  "Vital Throw",
  "Volt Switch",
  "Wake Up Slap",
  "Air Slash",
  "Brick Break",
  "Crush Claw",
  "Dragonbreath",
  "Drain Punch",
  "Fire Punch",
  "Grass Knot",
  "Horn Leech",
  "Ice Punch",
  "Mystical fire",
  "Razor Shell",
  "Relic Song",
  "Rock Slide",
  "Signal Beam",
  "Stomping Tantrum",
  "Thunder Punch",
  "Giga Drain",
  "Acrobatics",
  "Anchor Shot",
  "Aura Sphere",
  "Brine",
  "Counter",
  "Crunch",
  "Dark Pulse",
  "Dazzling Gleam",
  "Dig",
  "Discharge",
  "Dive",
  "Dragon Claw",
  "Drill Peck",
  "Drill Run",
  "Extrasensory",
  "Extreme Speed",
  "Fiery Dance",
  "Final Gambit",
  "Fire Lash",
  "Fire Pledge",
  "Flash Cannon",
  "Grass Pledge",
  "Gyro Ball",
  "Hidden Power (Bug)",
  "Hidden Power (Dark)",
  "Hidden Power (Dragon)",
  "Hidden Power (Electric)",
  "Hidden Power (Fairy)",
  "Hidden Power (Fighting)",
  "Hidden Power (Fire)",
  "Hidden Power (Flying)",
  "Hidden Power (Ghost)",
  "Hidden Power (Grass)",
  "Hidden Power (Ground)",
  "Hidden Power (Ice)",
  "Hidden Power (Normal)",
  "Hidden Power (Poison)",
  "Hidden Power (Psychic)",
  "Hidden Power (Rock)",
  "Hidden Power (Shadow)",
  "Hidden Power (Steel)",
  "Hidden Power (Water)",
  "Hyper Fang",
  "Hyperspace Hole",
  "Ice Ball",
  "Iron Head",
  "Lava Plume",
  "Leech Life",
  "Lunge",
  "Mega Punch",
  "Metal Burst",
  "Natures Madness",
  "Oblivion Wing",
  "Poison Jab",
  "Power Gem",
  "Power Trip",
  "Psyshock",
  "Punishment",
  "Razor Wind",
  "Reversal",
  "Scald",
  "Seed Bomb",
  "Shadow Ball",
  "Slam",
  "Spirit Shackle",
  "Strength",
  "Submission",
  "Throat Chop",
  "Water Pledge",
  "Waterfall",
  "X-Scissor",
  "Zen Headbutt",
  "Zing Zap",
  "Blaze Kick",
  "Body Slam",
  "Bounce",
  "Darkest Lariat",
  "Dragon Pulse",
  "Icicle Crash",
  "Liquidation",
  "Night Daze",
  "Psychic Fangs",
  "Secret Sword",
  "Shadow Blast",
  "Shadow Bone",
  "Shadow End",
  "Sky Uppercut",
  "Aqua Tail",
  "Attack Order",
  "Bug Buzz",
  "Dragon Hammer",
  "Earth Power",
  "Energy Ball",
  "First Impression",
  "Flamethrower",
  "Fly",
  "Hyper Voice",
  "Ice Beam",
  "Lands Wrath",
  "Leaf Blade",
  "Meteor Mash",
  "Muddy Water",
  "Multi Attack (Normal)",
  "Petal Blizzard",
  "Phantom Force",
  "Play Rough",
  "Pollen Puff",
  "Psychic",
  "Revelation Dance",
  "Rock Climb",
  "Sacred Sword",
  "Sludge Bomb",
  "Sparkling Aria",
  "Spectral Thief",
  "Surf",
  "Take Down",
  "Thousand Arrows",
  "Thousand Waves",
  "Thunderbolt",
  "Tri Attack",
  "Uproar",
  "Wild Charge",
  "Foul Play",
  "Heat wave",
  "High Horsepower",
  "Moonblast",
  "Sludge Wave",
  "Aeroblast",
  "Beak Blast",
  "Core Enforcer",
  "Crabhammer",
  "Cross Chop",
  "Diamond Storm",
  "Dragon Rush",
  "Dream Eater",
  "Dynamic Punch",
  "Earthquake",
  "egg Bomb",
  "Flying Press",
  "Frustration",
  "Fusion Bolt",
  "Fusion Flare",
  "Hammer Arm",
  "Heavy Slam",
  "Hyperspace Fury",
  "Ice Hammer",
  "Inferno",
  "Iron Tail",
  "Judgement (Normal)",
  "Jump Kick",
  "Magma Storm",
  "Moongeist Beam",
  "Photon Geyser",
  "Plasma Fists",
  "Psystrike",
  "Return",
  "Sacred Fire",
  "Searing Shot",
  "Spacial Rend",
  "Stone Edge",
  "Sunsteel Strike",
  "Wring Out",
  "Blizzard",
  "Clanging Scales",
  "Crush Grip",
  "Fire Blast",
  "Hurricane",
  "Hydro Pump",
  "Origin Pulse ",
  "Steam Eruption",
  "Thunder",
  "Belch",
  "Brave Bird",
  "close Combat",
  "Double Edge",
  "Dragon Ascent",
  "Fissure",
  "Flare Blitz",
  "Focus Blast",
  "Future Sight",
  "Guillotine",
  "Gunk Shot",
  "Head Charge",
  "Outrage",
  "Petal Dance",
  "Power Whip",
  "Precipice Blades",
  "Seed Flare",
  "Shadow Force",
  "Sheer Cold",
  "Solar Beam",
  "Superpower",
  "Synchronoise",
  "Techno Blast",
  "Thrash",
  "Trump Card",
  "Volt Tackle",
  "Woodhammer",
  "Zap Cannon",
  "Solar Blade",
  "Blue Flare",
  "Bolt Strike",
  "Burn Up",
  "Draco Meteor",
  "Fleur Canon",
  "High Jump Kick",
  "Leaf Storm",
  "Overheat",
  "Skull Bash",
  "Boomburst",
  "Doom Desire",
  "Freeze Shock",
  "Ice Burn",
  "Last Resort",
  "Light Of Ruin",
  "Psycho Boost",
  "Sky Attack",
  "Blast Burn",
  "Eruption",
  "Focus Punch",
  "Frenzy Plant ",
  "Giga Impact",
  "Head Smash",
  "Hydro Cannon",
  "Hyper Beam",
  "Mind Blown",
  "Roar Of Time",
  "Rock Wrecker",
  "Shell Trap",
  "Water Spout",
  "Prismatic Laser",
  "Apple Acid",
  "Aura Wheel",
  "Behemoth Bash",
  "Body Press",
  "Bolt Beak",
  "Branch Poke",
  "Breaking Swipe",
  "Clangorous Soul",
  "Court Change",
  "Decorate",
  "Dragon Darts",
  "Drum Beating",
  "Dynamax Cannon",
  "Eternabeam",
  "False Surrender",
  "Fishious Rend",
  "Grav Apple",
  "Jaw Lock",
  "Life Dew",
  "Magic Powder",
  "Meteor Assault",
  "No Retreat",
  "Obstruct",
  "Octolock",
  "Overdrive",
  "Pyro Ball",
  "Snap Trap",
  "Snipe Shot",
  "Spirit Break",
  "Steel Beam",
  "Strange Steam",
  "Stuff Cheeks",
  "Tar Shot",
  "Teatime"
];

var starterList = [
  "Caterpie",
  "Weedle",
  "Pidgey",
  "Rattata",
  "Alolan Rattata",
  "Spearow",
  "Ekans",
  "Pichu",
  "Pikachu",
  "Nidoran F",
  "Nidoran M",
  "Eevee",
  "Oddish",
  "Paras",
  "Venonant",
  "Diglett",
  "Alolan Diglett",
  "Meowth",
  "Alolan Meowth",
  "Galarian Meowth",
  "Poliwag",
  "Goldeen",
  "Eevee",
  "Sentret",
  "Hoothoot",
  "Ledyba",
  "Spinarak",
  "Zubat",
  "Chinchou",
  "Sunkern",
  "Hoppip",
  "Wooper",
  "Pineco",
  "Dunsparce",
  "Cleffa",
  "Igglybuff",
  "Togepi",
  "Magby",
  "Elekid",
  "Poochyena",
  "Zigzagoon",
  "Galarian Zigzagoon",
  "Wurmple",
  "Lotad",
  "Seedot",
  "Taillow",
  "Wingull",
  "Surskit",
  "Shroomish",
  "Slakoth",
  "Nincada",
  "Whismur",
  "Skitty",
  "Roselia",
  "Gulpin",
  "Luvdisc",
  "Starly",
  "Bidoof",
  "Kricketot",
  "Budew",
  "Burmy (Grass)",
  "Burmy (Ground)",
  "Burmy (Trash)",
  "Combee",
  "Pachirisu",
  "Buizel",
  "Cherubi",
  "Shellos",
  "Buneary",
  "Finneon",
  "Rotom",
  "Patrat",
  "Lillipup",
  "Purrloin",
  "Pansage",
  "Pansear",
  "Panpour",
  "Pidove",
  "Blitzle",
  "Roggenrola",
  "Woobat",
  "Drilbur",
  "Tympole",
  "Basculin (Red)",
  "Basculin (Blue)",
  "Foongus",
  "Shelmet",
  "Karrablast",
  "Bunnelby",
  "Fletchling",
  "Scatterbug",
  "Litleo",
  "Flabebe",
  "Skiddo",
  "Pancham",
  "Furfrou",
  "Espurr",
  "Honedge",
  "Spritzee",
  "Swirlix",
  "Inkay",
  "Malmar",
  "Binacle",
  "Skrelp",
  "Clauncher",
  "Helioptile",
  "Pikipek",
  "Yungoos",
  "Grubbin",
  "Crabrawler",
  "Oricorio (Baile)",
  "Oricorio (Pom-Pom)",
  "Oricorio (Pa'u)",
  "Oricorio (Sensu)",
  "Cutiefly",
  "Rockruff",
  "Wishwashi",
  "Mareanie",
  "Mudbray",
  "Dewpider",
  "Fomantis",
  "Morelull",
  "Salandit",
  "Stufful",
  "Bounsweet",
  "Togedemaru",
  "Skwovet",
  "Rookidee",
  "Blipbug",
  "Nickit",
  "Gossifleur",
  "Wooloo",
  "Chewtle",
  "Yamper",
  "Arrokuda"
];

var startertypeList = [
  "Normal",
  "Fighting",
  "Ghost",
  "Dark",
  "Psychic",
  "Fairy",
  "Flying",
  "Electric",
  "Water",
  "Fire",
  "Grass",
  "Poison",
  "Steel",
  "Dragon",
  "Bug",
  "Ice",
  "Rock",
  "Ground"
];

var studyList = [
  "Bulbasaur",
  "Squirtle",
  "Charmander",
  "Chikorita",
  "Totodile",
  "Cyndaquil",
  "Treecko",
  "Torchic",
  "Mudkip",
  "Turtwig",
  "Chimchar",
  "Piplup",
  "Snivy",
  "Oshawott",
  "Tepig",
  "Chespin",
  "Fennekin",
  "Froakie",
  "Litten",
  "Rowlet",
  "Popplio",
  "Grookey",
  "Sobble",
  "Scorbunny",
  "Baublehopper",
  "Geckglow",
  "Pupski"
];

var coinList = [
  "*It's side?!*",
  "Heads!",
  "Tails!",
];
var coinweight = [1, 50, 50];

var itemList = [
  "A Strange Round Stone",
  "A Nanab Berry",
  "A Razz Berry",
  "A Cocoa Poffin",
  "An Egg" + "\n" + "*Roll type using r!type*",
  "Some Honey" + "\n" + "*Roll type using r!type*",
  "A Crater Ball",
  "A Friendship Ball",
  "A Grepa Berry",
  "A Hondew Berry",
  "A Kelpsy Berry",
  "A Bag of Ore Dust" + "\n" + "*Roll type using r!type*",
  "A Poke Toy",
  "A Pinap Berry",
  "A Pink Apricot",
  "A Potion",
  "100 Crater Coins",
  "Some Ore" + "\n" + "*Roll type using r!type*"
];

var voidstrandList = [
  "1 Void Strand",
  "1 Void Strand",
  "1 Void Strand",
  "2 Void Strands",
  "2 Void Strands",
  "3 Void Strands"
];

var strangestoneList = [
  "Nothing",
  "Nothing",
  "Nothing",
  "Nothing",
  "Nothing",
  "Nothing",
  "Nothing",
  "Nothing",
  "Nothing",
  //Ore
  "Normal Ore",
  "Fighting Ore",
  "Ghost Ore",
  "Dark Ore",
  "Psychic Ore",
  "Fairy Ore",
  "Flying Ore",
  "Electric Ore",
  "Water Ore",
  "Fire Ore",
  "Grass Ore",
  "Poison Ore",
  "Steel Ore",
  "Dragon Ore",
  "Bug Ore",
  "Ice Ore",
  "Rock Ore",
  "Ground Ore",
  "Void Ore",
  "Nova Ore",
  //Ore x2
  "Normal Ore",
  "Fighting Ore",
  "Ghost Ore",
  "Dark Ore",
  "Psychic Ore",
  "Fairy Ore",
  "Flying Ore",
  "Electric Ore",
  "Water Ore",
  "Fire Ore",
  "Grass Ore",
  "Poison Ore",
  "Steel Ore",
  "Dragon Ore",
  "Bug Ore",
  "Ice Ore",
  "Rock Ore",
  "Ground Ore",
  "Void Ore",
  "Nova Ore",
  //Ore x3
  "Normal Ore",
  "Fighting Ore",
  "Ghost Ore",
  "Dark Ore",
  "Psychic Ore",
  "Fairy Ore",
  "Flying Ore",
  "Electric Ore",
  "Water Ore",
  "Fire Ore",
  "Grass Ore",
  "Poison Ore",
  "Steel Ore",
  "Dragon Ore",
  "Bug Ore",
  "Ice Ore",
  "Rock Ore",
  "Ground Ore",
  "Void Ore",
  "Nova Ore",
  //1 Bag
  "1 bag worth of Normal Dust",
  "1 bag worth of Fighting Dust",
  "1 bag worth of Ghost Dust",
  "1 bag worth of Dark Dust",
  "1 bag worth of Psychic Dust",
  "1 bag worth of Fairy Dust",
  "1 bag worth of Flying Dust",
  "1 bag worth of Electric Dust",
  "1 bag worth of Water Dust",
  "1 bag worth of Fire Dust",
  "1 bag worth of Grass Dust",
  "1 bag worth of Poison Dust",
  "1 bag worth of Steel Dust",
  "1 bag worth of Dragon Dust",
  "1 bag worth of Bug Dust",
  "1 bag worth of Ice Dust",
  "1 bag worth of Rock Dust",
  "1 bag worth of Ground Dust",
  "1 bag worth of Void Dust",
  "1 bag worth of Nova Dust",
  //2 Bags
  "2 bags worth of Normal Dust",
  "2 bags worth of Fighting Dust",
  "2 bags worth of Ghost Dust",
  "2 bags worth of Dark Dust",
  "2 bags worth of Psychic Dust",
  "2 bags worth of Fairy Dust",
  "2 bags worth of Flying Dust",
  "2 bags worth of Electric Dust",
  "2 bags worth of Water Dust",
  "2 bags worth of Fire Dust",
  "2 bags worth of Grass Dust",
  "2 bags worth of Poison Dust",
  "2 bags worth of Steel Dust",
  "2 bags worth of Dragon Dust",
  "2 bags worth of Bug Dust",
  "2 bags worth of Ice Dust",
  "2 bags worth of Rock Dust",
  "2 bags worth of Ground Dust",
  "2 bags worth of Void Dust",
  "2 bags worth of Nova Dust",
  //3 Bags
  "3 bags worth of Normal Dust",
  "3 bags worth of Fighting Dust",
  "3 bags worth of Ghost Dust",
  "3 bags worth of Dark Dust",
  "3 bags worth of Psychic Dust",
  "3 bags worth of Fairy Dust",
  "3 bags worth of Flying Dust",
  "3 bags worth of Electric Dust",
  "3 bags worth of Water Dust",
  "3 bags worth of Fire Dust",
  "3 bags worth of Grass Dust",
  "3 bags worth of Poison Dust",
  "3 bags worth of Steel Dust",
  "3 bags worth of Dragon Dust",
  "3 bags worth of Bug Dust",
  "3 bags worth of Ice Dust",
  "3 bags worth of Rock Dust",
  "3 bags worth of Ground Dust",
  "3 bags worth of Void Dust",
  "3 bags worth of Nova Dust"
];

var wildz1attackList = [
  "**Attack Move 1**! A Special Attack based move! Roll for damage using Wild Pokemon Sp. Atk, Trainer Pokemon Sp. Def and Trainer Pokemon HP!",
  "**Attack Move 2**! An Attack based move! Roll for damage using Wild Pokemon Atk, Trainer Pokemon Def and Trainer Pokemon HP!",
  "**Attack Move 3**! A Stat Lowering move! The Trainers Pokemon has a single stat lowered! Incoporate missing stats in damage rolls.",
  "**Attack Move 4**! A Stat Boosting based move! The Wild Pokemon has a single stat increased! Incoporate bonus in damage rolls."
];

var voidattackList = [
  "**Attack Move 1**! An Attack based move! Roll for damage using Wild Pokemon Attack / Special Attack, Trainer Pokemon Defense / Sp. Def and Trainer Pokemon HP!",
  "**Attack Move 2**! A Stat Lowering move! The Trainers Pokemon has a single stat lowered! Incoporate missing stats in damage rolls."
];

var blessingList = [
  "***You are not ready yet. But do not fear, for there will be a time that you will be.***" +
    "\n\n" +
    "What.. did they mean by that? In a flash of blinding light you cover your eyes, their Pokemon theirs, and when the light is gone so is the Legendary Pokemon. Was this all an illusion, a dream, a prank? " +
    "Confused on what had just happened you manage to regain your senses enough to head back home.. and maybe get some sleep.",
  "***You have raised your Pokemon well. I pray that they will continue to grow with this blessing.***" +
    "\n\n" +
    "What.. did they mean by that? A soft gentle light appears from their chest and floats over towards the Pokemon you sent out. It envelops them in a gentle hug of warm light before vanishing moments later. " +
    "As you go to ask the Legendary Pokemon what that was for they are gone. Is this their blessing? Your Pokemon looks to you and feels a little more powerful, though! " +
    "You call out a thank you, but there is no response back. Heading home for the day you can't wait to tell the others what had just happened." +
    "\n\n" +
    "**Type Immunity:** Your Pokemon has gained type immunity similar to the Legendary Pokemons' type, and will take 0 Damage from those typed moves! " +
    "They are also immune to those types status effects' (Ex// Electric Blessing = No Paralysis) during battle!" +
    "\n\n" +
    "**Optional Art Prompt:** Draw your Pokemon receiving its blessing from the legendary Pokemon! " +
    "Minimum requirements are Colored Full Bodies for both the Pokemon and the Legendary Pokemon with a Simple Background. " +
    "Submit it to the Expedition Art Folder to recieve a bonus of 1000 Crater Coins on top of the Crater Coins you would earn from the piece!"
];

var grasseggmoveList = [
  "Leafage",
  "Mega Drain",
  "Vine Whip",
  "Bullet Seed",
  "Razor Leaf",
  "Magical Leaf",
  "Needle Arm",
  "Leaf Tornado",
  "Grass Knot",
  "Horn Leech",
  "Giga Drain",
  "Grass Pledge",
  "Hidden Power (Grass)",
  "Seed Bomb",
  "Energy Ball",
  "Leaf Blade",
  "Petal Blizzard",
  "Petal Dance",
  "Power Whip",
  "Woodhammer",
  "Solar Blade",
  "Leaf Storm",
  "Frenzy Plant",
  "Grassy Glide",
  "Strength Sap",
  "Grassy Terrain",
  "Cotton Guard",
  "Grass Knot",
  "Worry Seed",
  "Aromatherapy",
  "Frenzy Plant",
  "Grass Whistle",
  "Ingrain",
  "Synthesis",
  "Cotton Spore",
  "Leech Seed",
  "Solar Beam",
  "Spore",
  "Sleep Powder",
  "Stun Spore"
];
var fireeggmoveList = [
  "Flame Charge",
  "Flame Wheel",
  "Incinerate",
  "Fire Fang",
  "Heat Crash",
  "Flame Burst",
  "Mystical Fire",
  "Fire Lash",
  "Fire Pledge",
  "Flamethrower",
  "Hidden Power (Fire)",
  "Lava Plume",
  "Blaze Kick",
  "Heat wave",
  "Inferno",
  "Flare Blitz",
  "Burn Up",
  "Overheat",
  "Blast Burn",
  "Eruption",
  "Flame Burst",
  "Blast Burn",
  "Will-o-Wisp",
  "Sunny Day"
];
var watereggmoveList = [
  "Clamp",
  "Whirlpool",
  "Water Gun",
  "Aqua Jet",
  "Water Pulse",
  "Razor Shell",
  "Brine",
  "Dive",
  "Hidden Power (Water)",
  "Scald",
  "Water Pledge",
  "Waterfall",
  "Liquidation",
  "Aqua Tail",
  "Muddy Water",
  "Surf",
  "Hydro Cannon",
  "Water Spout",
  "Life Dew",
  "Flip Turn",
  "Soak",
  "Aqua Ring",
  "Water Sport",
  "Rain Dance",
  "Bubblebeam",
  "Withdraw"
];
var electriceggmoveList = [
  "Thundershock",
  "Electro Web",
  "Shock Wave",
  "Thunder Fang",
  "Thunder Punch",
  "Discharge",
  "Hidden Power (Electric)",
  "Zing Zap",
  "Wild Charge",
  "Thunder",
  "Volt Tackle",
  "Zap Cannon",
  "Rising Voltage",
  "Eerie Impulse",
  "Electric Terrain",
  "Electrify",
  "Ion Deluge",
  "Magnetic Flux",
  "Nuzzle",
  "Parabolic Charge",
  "Electro Ball",
  "Volt Switch",
  "Charge Beam",
  "Magnet Rise",
  "Charge",
  "Thunder Wave",
  "Thunderbolt"
];
var flyingeggmoveList = [
  "Aerial Ace",
  "Air Cutter",
  "Mirror Move",
  "Pluck",
  "Sky Drop",
  "Acrobatics",
  "Hidden Power (Flying)",
  "Fly",
  "Brave Bird",
  "Feather Dance",
  "Dual Wingbeat",
  "Drill Peck",
  "Beak Blast",
  "Hurricane",
  "Air Slash",
  "Chatter",
  "Defog",
  "Roost",
  "Tailwind",
  "Bounce",
  "Peck"
];
var bugeggmoveList = [
  "Infestation",
  "Fell Stinger",
  "Pin Missile",
  "Struggle Bug",
  "Bug Bite",
  "Steamroller",
  "U-turn",
  "Hidden Power (Bug)",
  "Leech Life",
  "Lunge",
  "Attack Order",
  "Bug Buzz",
  "Pollen Puff",
  "Skitter Smack",
  "First Impression",
  "Powder",
  "Sticky Web",
  "Quiver Dance",
  "Rage Powder",
  "Defend Order",
  "Heal Order",
  "X-Scissor",
  "Signal Beam",
  "Silver Wind",
  "Tail Glow",
  "Fury Cutter",
  "Megahorn",
  "Spider Web",
  "String Shot"
];
var darkeggmoveList = [
  "Payback",
  "Snarl",
  "Bite",
  "Brutal Swing",
  "Sucker Punch",
  "Crunch",
  "Dark Pulse",
  "Hidden Power (Dark)",
  "Punishment",
  "Throat Chop",
  "Darkest Lariat",
  "Foul Play",
  "False Surrender",
  "Jaw Lock",
  "Lash Out",
  "Power Trip",
  "Parting Shot",
  "Hone Claws",
  "Quash",
  "Assurance",
  "Embargo",
  "Fling",
  "Nasty Plot",
  "Switcheroo",
  "Fake Tears",
  "Knock Off",
  "Memento",
  "Snatch",
  "Taunt",
  "Torment",
  "Beat Up",
  "Feint Attack",
  "Thief"
];
var psychiceggmoveList = [
  "Psywave",
  "Stored Power",
  "Psybeam",
  "Psycho Cut",
  "Hidden Power (Psychic)",
  "Psyshock",
  "Zen Headbutt",
  "Dream Eater",
  "Magic Powder",
  "Instruct",
  "Psychic Fangs",
  "Psychic Terrain",
  "Speed Swap",
  "Ally Switch",
  "Guard Split",
  "Heal Pulse",
  "Magic Room",
  "Power Split",
  "Synchronoise",
  "Telekinesis",
  "Wonder Room",
  "Gravity",
  "Guard Swap",
  "Heal Block",
  "Miracle Eye",
  "Power Swap",
  "Power Trick",
  "Trick Room",
  "Calm Mind",
  "Cosmic Power",
  "Extrasensory",
  "Imprison",
  "Magic Coat",
  "Role Play",
  "Skill Swap",
  "Trick",
  "Future Sight",
  "Mirror Coat",
  "Agility",
  "Amnesia",
  "Barrier",
  "Hypnosis",
  "Kinesis",
  "Light Screen",
  "Meditate",
  "Psychic",
  "Reflect",
  "Rest",
  "Teleport"
];
var dragoneggmoveList = [
  "Dual Chop",
  "Dragon Tail",
  "Dragonbreath",
  "Hidden Power (Dragon)",
  "Dragon Pulse",
  "Dragon Rush",
  "Outrage",
  "Draco Meteor",
  "Breaking Swipe",
  "Scale Shot",
  "Clanging Scales",
  "Dragon Claw",
  "Dragon Dance",
  "Twister"
];
var faireggmoveList = [
  "Fairy Wind",
  "Draining Kiss",
  "Dazzling Gleam",
  "Hidden Power (Fairy)",
  "Moonblast",
  "Aromatic Mist",
  "Baby Doll Eyes",
  "Fairy Lock",
  "Misty Terrain",
  "Play Rough",
  "Charm",
  "Moonlight",
  "Sweet Kiss"
];
var iceeggmoveList = [
  "Powder Snow",
  "Icicle Spear",
  "Icy Wind",
  "Aurora Beam",
  "Ice Punch",
  "Hidden Power (Ice)",
  "Ice Ball",
  "Icicle Crash",
  "Ice Beam",
  "Blizzard",
  "Sheer Cold",
  "Triple Axel",
  "Aurora Veil",
  "Freeze-Dry",
  "Frost Breath",
  "Glaciate",
  "Avalanche",
  "Ice Fang",
  "Hail",
  "Haze",
  "Mist"
];
var steeleggmoveList = [
  "Bullet Punch",
  "Magnet Bomb",
  "Mirror Shot",
  "Steel Wing",
  "Gyro Ball",
  "Hidden Power (Steel)",
  "Metal Burst",
  "Iron Tail",
  "Steel Beam",
  "Smart Strike",
  "Autotomize",
  "Heavy Slam",
  "Shift Gear",
  "Flash Cannon",
  "Iron Defense",
  "Metal Sound",
  "Meteor Mash",
  "Metal Claw"
];
var rockeggmoveList = [
  "Hidden Power (Rock)",
  "Meteor Beam",
  "Accelerock",
  "Smack Down",
  "Wide Guard",
  "Head Smash",
  "Power Gem",
  "Rock Polish",
  "Rock Wrecker",
  "Stealth Rock",
  "Stone Edge",
  "Rock Blast",
  "Rock Tomb",
  "Ancient Power",
  "Rollout",
  "Rockslide"
];
var groundeggmoveList = [
  "Hidden Power (Ground)",
  "Scorching Sands",
  "High Horsepower",
  "Shore Up",
  "Stomping Tantrum",
  "Rototiller",
  "Bulldoze",
  "Drill Run",
  "Earth Power",
  "Mud Bomb",
  "Mud Shot",
  "Mud Sport",
  "Sand Tomb",
  "Bone Rush",
  "Magnitude",
  "Spikes",
  "Bone Club",
  "Dig",
  "Earthquake",
  "Fissure",
  "Sand Attack"
];
var fightingeggmoveList = [
  "Vaccum Wave",
  "Power Up Punch",
  "Hidden Power (Fighting)",
  "Body Press",
  "Coaching",
  "Mat Block",
  "Circle Throw",
  "Final Gambit",
  "Low Sweep",
  "Quick Guard",
  "Sacred Sword",
  "Storm Throw",
  "Aura Sphere",
  "Close Combat",
  "Drain Punch",
  "Focus Blast",
  "Force Palm",
  "Hammer Arm",
  "Wake-Up Slap",
  "Arm Thrust",
  "Brick Break",
  "Bulk Up",
  "Focus Punch",
  "Revenge",
  "Sky Uppercut",
  "Superpower",
  "Cross Chop",
  "Detect",
  "Dynamic Punch",
  "Mach Punch",
  "Reversal",
  "Triple Kick",
  "Vital Throw",
  "Counter",
  "Double Kick",
  "High Jump Kick",
  "Jump Kick",
  "Karate Chop",
  "Low Kick",
  "Rolling Kick",
  "Seismic Toss",
  "Submission"
];
var ghosteggmoveList = [
  "Shadow Sneak",
  "Hidden Power (Ghost)",
  "Phantom Force",
  "Hex",
  "Ominous Wind",
  "Shadow Claw",
  "Astonish",
  "Grudge",
  "Shadow Punch",
  "Curse",
  "Destiny Bond",
  "Nightmare",
  "Shadow Ball",
  "Spite",
  "Confuse Ray",
  "Lick"
];
var poisoneggmoveList = [
  "Acid",
  "Acid Spray",
  "Hidden Power (Poison)",
  "Purify",
  "Toxic Thread",
  "Belch",
  "Venom Drench",
  "Clear Smog",
  "Coil",
  "Sludge Wave",
  "Venoshock",
  "Cross Poison",
  "Gastro Acid",
  "Gunk Shot",
  "Poison Jab",
  "Toxic Spikes",
  "Poison Fang",
  "Poison Tail",
  "Sludge Bomb",
  "Acid Armor",
  "Poison Gas",
  "Poison Powder",
  "Sludge",
  "Smog",
  "Toxic"
];
var normaleggmoveList = [
  "Constrict",
  "Hidden Power (Normal)",
  "Terrain Pulse",
  "Laser Focus",
  "Tearful Look",
  "Boombusrt",
  "Confide",
  "Hold Back",
  "Noble Roar",
  "Play Nice",
  "After You",
  "Bestow",
  "Chip Away",
  "Echoed Voice",
  "Entrainment",
  "Head Charge",
  "Retaliate",
  "Round",
  "Shell Smash",
  "Simple Beam",
  "Tail Slap",
  "Work Up",
  "Acupressure",
  "Captivate",
  "Copycat",
  "Crush Grip",
  "Double Hit",
  "Feint",
  "Giga Impact",
  "Last Resort",
  "Lucky Chant",
  "Me First",
  "Natural Gift",
  "Rock Climb",
  "Trump Card",
  "Wring Out",
  "Assist",
  "Block",
  "Camouflage",
  "Covet",
  "Crush Claw",
  "Endeavor",
  "Facade",
  "Fake Out",
  "Follow Me",
  "Hepling Hand",
  "Howl",
  "Hyper Voice",
  "Nature Power",
  "Odor Sleuth",
  "Recycle",
  "Refresh",
  "Secret Power",
  "Slack Off",
  "Smelling Salts",
  "Spit Up",
  "Stockpile",
  "Swallow",
  "Teeter Dance",
  "Uproar",
  "Weather Ball",
  "Wish",
  "Attract",
  "Yawn",
  "Baton Pass",
  "Belly Drum",
  "Encore",
  "Endure",
  "Extreme Speed",
  "False Swipe",
  "Flail",
  "Foresight",
  "Frustration",
  "Heal Bell",
  "Lock-On",
  "Mean Look",
  "Mind Reader",
  "Morning Sun",
  "Pain Split",
  "Perish Song",
  "Present",
  "Protect",
  "Psych Up",
  "Rapid Spin",
  "Return",
  "Safeguard",
  "Scary Face",
  "Sketch",
  "Sleep Talk",
  "Snore",
  "Swagger",
  "Sweet Scent",
  "Bide",
  "Bind",
  "Body Slam",
  "Comet Punch",
  "Conversion",
  "Cut",
  "Defense Curl",
  "Disable",
  "Dizzy Punch",
  "Double Slap",
  "Double Team",
  "Double Edge",
  "Explosion",
  "Flash",
  "Focus Energy",
  "Fury Attack",
  "Fury Swipes",
  "Glare",
  "Growl",
  "Growth",
  "Guillotine",
  "Harden",
  "Headbutt",
  "Horn Attack",
  "Horn Drill",
  "Hyper Beam",
  "Hyper Fang",
  "Leer",
  "Lovely Kiss",
  "Mega Kick",
  "Mega Punch",
  "Metronome",
  "Mimic",
  "Minimize",
  "Quick Attack",
  "Rage",
  "Razor Wind",
  "Recover",
  "Roar",
  "Scratch",
  "Screech",
  "Self-Destruct",
  "Sing",
  "Skull Bash",
  "Slam",
  "Smokescreen",
  "Sonic Boom",
  "Spike Cannon",
  "Splash",
  "Stomp",
  "Strength",
  "Substitute",
  "Super Fang",
  "Swift",
  "Swords Dance",
  "Tackle",
  "Tail Whip",
  "Take Down",
  "Thrash",
  "Tri-Attack",
  "Vice-Grip",
  "Wrap"
];

var evocrystalList = [
  "Unfortunately (or not-so unfortunately if this was your intent) When your Pokemon evolved, **their type changed to that of the type of Crystal they were holding!**\n\n" +
  "*Please consult a moderator to see if this change came with concequences.*",
  "Unfortunately (or not-so unfortunately if this was your intent) When your Pokemon evolved, **their type changed to that of the type of Crystal they were holding!**\n\n" +
  "*Please consult a moderator to see if this change came with concequences.*",
  "Unfortunately (or not-so unfortunately if this was your intent) When your Pokemon evolved, **their type changed to that of the type of Crystal they were holding!**\n\n" +
  "*Please consult a moderator to see if this change came with concequences.*",
  "Dispite taking the risk and using Crystal that doesn't match your Pokemon's typing, **their type remains unchanged!**",
  "Dispite taking the risk and using Crystal that doesn't match your Pokemon's typing, **their type remains unchanged!**",
  "Dispite taking the risk and using Crystal that doesn't match your Pokemon's typing, **their type remains unchanged!**",
  "Dispite taking the risk and using Crystal that doesn't match your Pokemon's typing, **their type remains unchanged!**",
  "Dispite taking the risk and using Crystal that doesn't match your Pokemon's typing, **their type remains unchanged!**",
  "Dispite taking the risk and using Crystal that doesn't match your Pokemon's typing, **their type remains unchanged!**",
  "Dispite taking the risk and using Crystal that doesn't match your Pokemon's typing, **their type remains unchanged!**",
];

var evogemstoneList = [
  "When your Pokemon evolved, **their type changed to that of the type of Gemstone they were holding!**\n\n" +
  "*Please consult a moderator to see if this change came with concequences.*",
  "When your Pokemon evolved, **their type changed to that of the type of Gemstone they were holding!**\n\n" +
  "*Please consult a moderator to see if this change came with concequences.*",
  "When your Pokemon evolved, **their type changed to that of the type of Gemstone they were holding!**\n\n" +
  "*Please consult a moderator to see if this change came with concequences.*",
  "When your Pokemon evolved, **their type changed to that of the type of Gemstone they were holding!**\n\n" +
  "*Please consult a moderator to see if this change came with concequences.*",
  "When your Pokemon evolved, **their type changed to that of the type of Gemstone they were holding!**\n\n" +
  "*Please consult a moderator to see if this change came with concequences.*",
  "When your Pokemon evolved, **their type changed to that of the type of Gemstone they were holding!**\n\n" +
  "*Please consult a moderator to see if this change came with concequences.*",
  "When your Pokemon evolved, **their type changed to that of the type of Gemstone they were holding!**\n\n" +
  "*Please consult a moderator to see if this change came with concequences.*",
  "When your Pokemon evolved, **their type changed to that of the type of Gemstone they were holding!**\n\n" +
  "*Please consult a moderator to see if this change came with concequences.*",
  "When your Pokemon evolved, **their type changed to that of the type of Gemstone they were holding!**\n\n" +
  "Please consult a moderator to see if this change came with concequences.",
  "Dispite taking the risk and using a Polished Gemstone that doesn't match your Pokemon's typing, **their type remains unchanged**!"
];

var useoreList = [
  "Success! **Your Pokemon's type has changed to match the type of Ore used on them!**",
  "Success! **Your Pokemon's type has changed to match the type of Ore used on them!**",
  "Success! **Your Pokemon's type has changed to match the type of Ore used on them!**",
  "Oh no! The Ore used on your Pokemon has gone to waste. **Their type remains unchanged.**"
];
//evo commands
//-crystal needs a 30% chance of type change
//-gemstone needs a 90% chance of type change
//-ore needs a 75% chance of type change

module.exports = {
  // classList: classList,
  // backgroundCollection: backgroundCollection,
  // raceList: raceList,
  pokemonList: pokemonList,
  legendaryList: legendaryList,
  typeList: typeList,
  moveList: moveList,
  starterList: starterList,
  startertypeList: startertypeList,
  studyList: studyList,
  coinList: coinList,
  itemList: itemList,
  voidstrandList: voidstrandList,
  strangestoneList: strangestoneList,
  wildz1attackList: wildz1attackList,
  voidattackList: voidattackList,
  blessingList: blessingList,

  grasseggmoveList: grasseggmoveList,
  fireeggmoveList: fireeggmoveList,
  watereggmoveList: watereggmoveList,
  electriceggmoveList: electriceggmoveList,
  flyingeggmoveList: flyingeggmoveList,
  bugeggmoveList: bugeggmoveList,
  darkeggmoveList: darkeggmoveList,
  psychiceggmoveList: psychiceggmoveList,
  dragoneggmoveList: dragoneggmoveList,
  faireggmoveList: faireggmoveList,
  iceeggmoveList: iceeggmoveList,
  steeleggmoveList: steeleggmoveList,
  rockeggmoveList: rockeggmoveList,
  groundeggmoveList: groundeggmoveList,
  fightingeggmoveList: fightingeggmoveList,
  ghosteggmoveList: ghosteggmoveList,
  poisoneggmoveList: poisoneggmoveList,
  normaleggmoveList: normaleggmoveList,
  
  evocrystalList: evocrystalList,
  evogemstoneList: evogemstoneList,
  useoreList: useoreList,
};
